
[global]
background = "#e9ebf0"
foreground = "#171c1f"
frame_color = "#ca8c70"

[urgency_low]
background = "#e9ebf0"
foreground = "#63787d"
frame_color = "#63787d"

[urgency_normal]
background = "#e9ebf0"
foreground = "#171c1f"
frame_color = "#ca8c70"

[urgency_critical]
background = "#e9ebf0"
foreground = "#171c1f"
frame_color = "#c0696b"
