
[global]
background = "#2b3538"
foreground = "#dddecf"
frame_color = "#93c9a1"

[urgency_low]
background = "#2b3538"
foreground = "#839e9a"
frame_color = "#839e9a"

[urgency_normal]
background = "#2b3538"
foreground = "#dddecf"
frame_color = "#93c9a1"

[urgency_critical]
background = "#2b3538"
foreground = "#dddecf"
frame_color = "#e67e80"
