
[global]
background = "#232a2e"
foreground = "#dddecf"
frame_color = "#9bb5cf"

[urgency_low]
background = "#232a2e"
foreground = "#839e9a"
frame_color = "#839e9a"

[urgency_normal]
background = "#232a2e"
foreground = "#dddecf"
frame_color = "#9bb5cf"

[urgency_critical]
background = "#232a2e"
foreground = "#dddecf"
frame_color = "#e67e80"
